# 站点标题
site_name: CSharp学习之路

# 站点URL
site_url: https://finneganwill.github.io/material-csharp

# 关联远程仓库
repo_url: https://github.com/finneganwill/material-csharp
repo_name: finneganwill/material-csharp

# 版权声明
copyright: Copyright &copy; 2022 - 2023 Finnegan Will

# 导航
nav:
    - Home: index.md
    - 入门: 
      - '认知C#': '入门/00 认识CSharp.md'
      - '数据类型': '入门/01 数据类型.md'
      - '运算符': '入门/02 运算符.md'
      - '控制语句': '入门/03 控制语句.md'
      - '数据结构': '入门/04 数据结构.md'
      - '类与对象': '入门/05 类与对象.md'
      - '抽象类与接口': '入门/06 抽象类与接口.md'
      - '异常处理': '入门/07 异常处理.md'

# 主题设置
theme:
  name: material
  # 语言 英文：language: en
  language: zh

  # 图标
  icon:
    repo: fontawesome/brands/github
  
  # 标题栏
  features:
    # 导航选项卡
    - navigation.tabs
    # 返回顶部
    - navigation.top
    # 目录跟随
    - toc.follow
    # 代码块复制
    - content.code.copy
    # 代码注释
    - content.code.annotate
    # 标题栏移动隐藏
    # - header.autohide
    # Ajax加载，大型网站可开启
    # - navigation.instant
    # URL锚点跟踪
    - navigation.tracking
    # footer 页面底部
    - navigation.footer

  # 调色板
  palette: 
    # light 明亮模式
    - scheme: default
      # emphasize 强调颜色
      accent: deep orange
      # header 头
      primary: blue grey
      # switch 开关
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # dark
    - scheme: slate
      # emphasize
      accent: deep orange
      # header
      primary: black
      # switch
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# 附加组件
extra:
  # 社交
  social:
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/698590186?spm_id_from=333.1007.0.0
      name: BiliBili

    - icon: fontawesome/brands/weibo
      link: https://github.com/finneganwill/material-csharp
      name: 微博

  # 分析
  analytics: 
    # 分析器
    provider: google
    property: G-XXXXXXXXXX

    # 反馈设置
    feedback:
      title: 本文章对您是否有帮助？
      ratings:
        - icon: material/emoticon-happy-outline
          name: 感谢帮助！
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: 有待提升！
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="" target="_blank" rel="noopener">feedback form</a>.


# MD扩展
markdown_extensions:
  # 代码高亮
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  # 文本标记：下划线，高亮，删除
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

  # 目录
  - toc:
      # 段落锚链接符号
      permalink: ⚓︎
      # 目录深度
      toc_depth: 3

      # 锚链接说明
      # permalink_title: Anchor link to this section for reference
      # 标题
      # title: Content

# 插件
plugins:
  # 时间插件
  - git-revision-date-localized:
      enabled: !ENV [CI, false]
      type: timeago
      enable_creation_date: true
      fallback_to_build_date: true