# 站点标题
site_name: .Net Material

# 站点URL
site_url: https://finneganwill.github.io/material-dotnet

# 关联远程仓库
repo_url: https://github.com/finneganwill/material-dotnet
repo_name: finneganwill/material-dotnet

# 版权声明
copyright: Copyright &copy; 2022 - 2023 Finnegan Will

# 导航
nav:
    - Home: 'index.md'

    - C#: 
      - C#基础:
        - 认识C#: 'csharp-foundation/00 认识CSharp.md'
        - 数据类型: 'csharp-foundation/01 数据类型.md'
        - 运算符: 'csharp-foundation/02 运算符.md'
        - 控制语句: 'csharp-foundation/03 控制语句.md'
        - 数据结构: 'csharp-foundation/04 数据结构.md'
        - 类与对象: 'csharp-foundation/05 类与对象.md'
        - 抽象类与接口: 'csharp-foundation/06 抽象类与接口.md'
        - 异常处理: 'csharp-foundation/07 异常处理.md'

      - C#进阶: 
        - 索引器: 'csharp-advanced/01 索引器.md'
        - 委托: 'csharp-advanced/02 委托与事件.md'
        - 泛型: 'csharp-advanced/03 泛型.md'
        - 集合: 'csharp-advanced/04 集合.md'
        - 特性: 'csharp-advanced/05 特性.md'
        - 反射: 'csharp-advanced/06 反射.md'
        - 多线程: 'csharp-advanced/07 多线程.md'
        - 文件处理: 'csharp-advanced/08 文件处理.md'
#      - 匿名函数: csharp-advanced/
#      - 指针变量: csharp-advanced/

    - LINQ:
      - 了解LINQ: 'linq/01 了解LINQ.md'
      - 查询语法: 'linq/02 查询语法.md'

    - ADO.NET:
      - 了解ADO.NET: 'adonet/01 了解ADO.NET.md'
      - 数据提供程序: 'adonet/02 数据提供程序.md'
      - 数据集: 'adonet/03 数据集.md'
      - 数据类型映射: 'adonet/04 数据类型映射.md'
      - 连接数据源: 'adonet/05 连接数据源.md'
      - 检索和修改数据: 'adonet/06 检索和修改数据.md'

    - EF Core:
      - 了解EF Core: 'ef-core/01 了解EF Core.md'

    - ASP.NET Core: 
      - 了解ASP.NET: 'aspnet-core/01 了解ASP.NET.md'

    - 关于: 
      - Author: 'common/author.md'
      - MkDocs: 'common/mkdocs.md'
      - Thanks: 'common/thanks.md'


# 主题设置
theme:
  name: material
  # 语言 英文：language: en
  language: zh

  # 图标
  icon:
    repo: fontawesome/brands/github
  
  # 标题栏
  features:
    # 导航选项卡
    - navigation.tabs
    # 返回顶部
    - navigation.top
    # 目录跟随
    - toc.follow
    # 代码块复制
    - content.code.copy
    # 代码注释
    - content.code.annotate
    # 标题栏移动隐藏
    # - header.autohide
    # Ajax加载，大型网站可开启
    # - navigation.instant
    # URL锚点跟踪
    - navigation.tracking
    # footer 页面底部
    - navigation.footer

  # 调色板
  palette: 
    # light 明亮模式
    - scheme: default
      # emphasize 强调颜色
      accent: cyan
      # header 头
      primary: orange
      # switch 开关
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # dark
    - scheme: slate
      # emphasize
      accent: orange
      # header
      primary: black
      # switch
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# 附加组件
extra:
  # 社交
  social:
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/698590186?spm_id_from=333.1007.0.0
      name: BiliBili

    - icon: fontawesome/brands/weibo
      link: https://github.com/finneganwill/material-csharp
      name: 微博

  # 分析
  analytics: 
    # 分析器
    provider: google
    property: G-XXXXXXXXXX

    # 反馈设置
    feedback:
      title: 本文章对您是否有帮助？
      ratings:
        - icon: material/emoticon-happy-outline
          name: 感谢帮助！
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: 有待提升！
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="" target="_blank" rel="noopener">feedback form</a>.

# MD扩展
markdown_extensions:
  # 脚注
  - footnotes
  # 代码高亮
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  # 提示与警告
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  # 文本标记：下划线，高亮，删除
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

  # emoji
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  # 目录
  - toc:
      # 段落锚链接符号
      permalink: ⚓︎
      # 目录深度
      toc_depth: 3

      # 锚链接说明
      # permalink_title: Anchor link to this section for reference
      # 标题
      # title: Content

  # 图像
  - attr_list
  - md_in_html

  # 列表
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  # 内容选项卡
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 


# 插件
plugins:
  # 时间插件
  - git-revision-date-localized:
      enabled: !ENV [CI, false]
      type: datetime
      enable_creation_date: true
      fallback_to_build_date: true

  # 图像缩放插件
  - glightbox