# 站点标题
site_name: .Net Material

# 站点URL
site_url: https://finneganwill.github.io/material-dotnet

# 关联远程仓库
repo_url: https://github.com/finneganwill/material-dotnet
repo_name: finneganwill/material-dotnet

# 版权声明
copyright: Copyright &copy; 2022 - 2023 Finnegan Will

# 导航
nav:
    - Home: 'index.md'

    - 博客记录:
      - 2023年5月:
        - Init: 'blogs/202305/init.md'
      - 2023年4月:
        - Title: 'blogs/202304/test.md'

    - 技术学习:
      - 摘要: teches/Abstract.md
      - C#: 
        - 认识C#: 'teches/csharp/00-认识CSharp.md'
        - 数据类型: 'teches/csharp/01-数据类型.md'
        - 运算符: 'teches/csharp/02-运算符.md'
        - 控制语句: 'teches/csharp/03-控制语句.md'
        - 数据结构: 'teches/csharp/04-数据结构.md'
        - 类与对象: 'teches/csharp/05-类与对象.md'
        - 抽象类与接口: 'teches/csharp/06-抽象类与接口.md'
        - 异常处理: 'teches/csharp/07-异常处理.md'
        - 常用类: 'teches/csharp/08-常用类.md'
        - 索引器: 'teches/csharp/09-索引器.md'
        - 委托: 'teches/csharp/10-委托与事件.md'
        - 泛型: 'teches/csharp/11-泛型.md'
        - 集合: 'teches/csharp/12-集合.md'
        - 特性: 'teches/csharp/13-特性.md'
        - 反射: 'teches/csharp/14-反射.md'
        - 多线程: 'teches/csharp/15-多线程.md'
        - 文件处理: 'teches/csharp/16-文件处理.md'
  #      - 匿名函数: teches/csharp/
  #      - 指针变量: teches/csharp/

      - LINQ:
        - 了解LINQ: 'teches/linq/01-了解LINQ.md'
        - 查询语法: 'teches/linq/02-查询语法.md'
        - 方法语法: 'teches/linq/03-方法语法.md'
        - 标准查询运算符: 
          - 标准查询运算符方法: 'teches/linq/04-标准查询运算符方法.md'
          - 投影运算: 'teches/linq/05-投影运算.md'
          - 筛选运算: 'teches/linq/06-筛选运算.md'
          - 排序运算: 'teches/linq/07-排序运算.md'
          - 数据分组: 'teches/linq/08-数据分组.md'

      - ADO.NET:
        - 了解ADO.NET: 'teches/adonet/01-了解ADO.NET.md'
        - 数据提供程序: 'teches/adonet/02-数据提供程序.md'
        - 数据集: 'teches/adonet/03-数据集.md'
        - 数据类型映射: 'teches/adonet/04-数据类型映射.md'
        - 连接数据源: 'teches/adonet/05-连接数据源.md'
        - 创建命令与配置参数: 'teches/adonet/06-创建命令与配置参数.md'
        - 检索和修改数据: 'teches/adonet/07-检索和修改数据.md'
        - 事务与并发性: 'teches/adonet/08-事务与并发性.md'

      - EF Core:
        - 了解EF Core: 'teches/ef-core/01-了解EF Core.md'
        - DbContext: 'teches/ef-core/02-DbContext.md'

      - ASP.NET Core: 
        - 了解ASP.NET: 'teches/aspnet-core/01 了解ASP.NET.md'

    - BUG修复:
      - Init: 'bugs/init.md'

    - 生活留言:
      - Init: 'life/init.md'

    - 关于: 
      - Author: 'common/author.md'
      - MkDocs: 'common/mkdocs.md'
      - Thanks: 'common/thanks.md'


# 主题设置
theme:
  name: material
  # 语言 英文：language: en
  language: zh

  # 图标
  icon:
    repo: fontawesome/brands/github
  
  # 标题栏
  features:
    # 导航选项卡
    - navigation.tabs
    # 返回顶部
    - navigation.top
    # 目录跟随
    - toc.follow
    # 代码块复制
    - content.code.copy
    # 代码注释
    - content.code.annotate
    # 标题栏移动隐藏
    # - header.autohide
    # Ajax加载，大型网站可开启
    # - navigation.instant
    # URL锚点跟踪
    - navigation.tracking
    # footer 页面底部
    - navigation.footer

  # 调色板
  palette: 
    # light 明亮模式
    - scheme: default
      # emphasize 强调颜色
      accent: cyan
      # header 头
      primary: orange
      # switch 开关
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # dark
    - scheme: slate
      # emphasize
      accent: orange
      # header
      primary: black
      # switch
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# 附加组件
extra:
  # 社交
  social:
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/698590186?spm_id_from=333.1007.0.0
      name: BiliBili

    - icon: fontawesome/brands/weibo
      link: https://github.com/finneganwill/material-csharp
      name: 微博

  # 分析
  analytics: 
    # 分析器
    provider: google
    property: G-XXXXXXXXXX

    # 反馈设置
    feedback:
      title: 本文章对您是否有帮助？
      ratings:
        - icon: material/emoticon-happy-outline
          name: 感谢帮助！
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: 有待提升！
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="" target="_blank" rel="noopener">feedback form</a>.

# MD扩展
markdown_extensions:
  # 脚注
  - footnotes
  # 代码高亮
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  # 提示与警告
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  # 文本标记：下划线，高亮，删除
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

  # emoji
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  # 目录
  - toc:
      # 段落锚链接符号
      permalink: ⚓︎
      # 目录深度
      toc_depth: 3

      # 锚链接说明
      # permalink_title: Anchor link to this section for reference
      # 标题
      # title: Content

  # 图像
  - attr_list
  - md_in_html

  # 列表
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  # 内容选项卡
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 


# 插件
plugins:
  # 时间插件
  - git-revision-date-localized:
      enabled: !ENV [CI, false]
      type: datetime
      enable_creation_date: true
      fallback_to_build_date: true

  # 图像缩放插件
  - glightbox